# vars/default.yml - ProtonVPN configuration for Synology
#
# Update these values before running the playbook.

---
# =============================================================================
# ProtonVPN Configuration
# =============================================================================

# VPN profile name (shown in DSM UI)
vpn_profile_name: "ProtonVPN_UK"

# Username suffix for ProtonVPN features
# Options:
#   +b:4  - Enforce exit through specific server (check .ovpn file for number)
#   +f1   - Anti-malware filtering (NetShield)
#   +f2   - Anti-malware + ad-blocking
#   +nr   - Moderate NAT
# Can be combined, e.g.: "+b:4+f2"
# Leave empty for no suffix
vpn_username_suffix: "+f2"

# =============================================================================
# Network Configuration
# =============================================================================

# Local network CIDR (traffic to local network bypasses VPN)
local_network_cidr: "10.0.4.0/24"

# Synology IP address (used in display messages)
synology_ip: "10.0.4.2"

# =============================================================================
# Paths
# =============================================================================

# Where to store VPN config files on Synology
vpn_config_dir: "/volume1/vpn-config"

# OpenVPN config file (download from ProtonVPN and place here)
ovpn_config_file: "{{ vpn_config_dir }}/protonvpn.ovpn"
