#!/bin/bash
# Disable ProtonVPN Kill Switch
# Restores normal network access
#
# Generated by pod-synology-vpn

# Flush rules
iptables -F OUTPUT
iptables -F INPUT
iptables -F FORWARD

# Set default policies to ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT

echo "Kill switch disabled - normal network access restored"
