#!/bin/bash
# Disable ProtonVPN Kill Switch
# Restores normal network access
#
# Generated by pod-synology-vpn
#
# NOTE: Does NOT flush FORWARD chain to preserve Docker's rules

# Flush INPUT and OUTPUT only
iptables -F OUTPUT
iptables -F INPUT

# Set default policies to ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P INPUT ACCEPT

# Remove our custom FORWARD rules (Docker's rules stay intact)
iptables -D FORWARD -s 172.16.0.0/12 -d 10.0.4.0/24 -j ACCEPT 2>/dev/null
iptables -D FORWARD -s 10.0.4.0/24 -d 172.16.0.0/12 -j ACCEPT 2>/dev/null
iptables -D FORWARD -s 192.168.0.0/16 -d 10.0.4.0/24 -j ACCEPT 2>/dev/null
iptables -D FORWARD -s 10.0.4.0/24 -d 192.168.0.0/16 -j ACCEPT 2>/dev/null

echo "Kill switch disabled - normal network access restored"
echo "NOTE: Docker FORWARD rules preserved"
